"""empty message

Revision ID: 2ac0ca5d49fc
Revises: 9ce605484290
Create Date: 2026-06-11 03:19:47.481043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac0ca5d49fc'
down_revision = '9ce605484290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('premios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.String(length=360), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_local', sa.String(length=120), nullable=False),
    sa.Column('equipo_visitante', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('etapa', sa.String(length=24), nullable=False),
    sa.Column('resultado', sa.Enum('EMPATE', 'GANA_LOCAL', 'GANA_VISITANTE', name='resultado'), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_prediction', sa.Enum('EMPATE', 'GANA_LOCAL', 'GANA_VISITANTE', name='resultado'), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediccion')
    op.drop_table('partidos')
    op.drop_table('premios')
    # ### end Alembic commands ###
