"""empty message

Revision ID: 619038c147d6
Revises: 2ac0ca5d49fc
Create Date: 2026-06-13 01:16:05.928680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619038c147d6'
down_revision = '2ac0ca5d49fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('premios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('torneo_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'torneo', ['torneo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('premios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('torneo_id')

    with op.batch_alter_table('prediccion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
